src/alphabets/mod.rs
src/data_structures/rank_select.rs
src/data_structures/suffix_array.rs

More specifically:
- `BitvSet` => `BitSet`
- `Bitv` => `BitVec`

Fix the build for Rust master

---

src/alphabets/mod.rs
src/alphabets/protein.rs

This adds (very basic) support for proteins.

alphabets: add protein alphabet

---

src/io/fasta.rs

FASTA reader was wrongly consuming the line after the last seq in entry; the sequence included the header of the next entry.

Fix FASTA reader

---

src/alignment/distance.rs
src/alignment/pairwise.rs
src/alphabets/dna.rs
src/alphabets/mod.rs
src/data_structures/bitenc.rs
src/data_structures/fmindex.rs
src/data_structures/rank_select.rs
src/data_structures/smallints.rs
src/data_structures/suffix_array.rs
src/io/bed.rs
src/io/fasta.rs
src/io/fastq.rs
src/pattern_matching/bom.rs
src/pattern_matching/ukkonen.rs

I used [rust-clippy](https://github.com/Manishearth/rust-clippy) on this project and save a few false positives, the warnings should be useful, so I fixed them. Nice project! :smile:

fixed a few clippy warnings

---

src/scores/blosum62.rs

Pardon the previous error. I'll complete the rest of the matrices also.
Thanks.

fix(blosum62.rs): the lookup function should be ..Y,Z,X not X,Y,Z

---

src/scores/mod.rs
src/scores/pam200.rs

Fixed testcase errors in PAM200, and enabled the `scores` module

---

.travis.yml

This should make doc upload easier and also speed up the build.
Fixes #16

Use travis-cargo and sudo: false

---

src/alignment/distance.rs
src/alignment/mod.rs
src/alphabets/mod.rs
src/data_structures/bwt.rs
src/data_structures/fmindex.rs
src/data_structures/qgram_index.rs
src/data_structures/rank_select.rs
src/data_structures/suffix_array.rs
src/io/fasta.rs
src/io/fastq.rs
src/stats/logprobs.rs
src/utils.rs

This fixes another set of clippy warnings, and also makes use of HashMap's entry API in qgram_index.rs

fix clippy warnings

---

src/alphabets/dna.rs
src/data_structures/fmindex.rs

Reimplement reverse complement as functions. Support for IUPAC alphabet.

---

src/io/bed.rs
src/io/gff.rs
src/io/mod.rs

Hello,
I used the bed parser for create this gff/gtf parser.
They doesn't support the attributes field actually.
Thanks for you job

Basic gff/gtf parser

---

src/alignment/mod.rs
src/alignment/pairwise.rs

added additional tests and corrected results on some existing tests.
I believe the test for test_issue12_2 was incorrect -- the current code find an alignment with one fewer gap & a higher score.

traceback over S/I/D matrices,

---

CHANGELOG.md
Cargo.toml
src/data_structures/suffix_array.rs

* Provide a specialized implementation of `sample` for `RawSuffixArray`.
* Increase sampling rate in test case (currently causes a failure).

Refactor suffix array sampling and failing test case.

---

src/io/bed.rs

I'm working on something else and this failed doctest was bugging me.

Fixing failed compile on io::bed doctest

---

src/alignment/mod.rs
src/alignment/pairwise.rs
src/data_structures/fmindex.rs
src/data_structures/smallints.rs
src/data_structures/suffix_array.rs
src/io/bed.rs
src/io/fasta.rs
src/io/fastq.rs
src/io/gff.rs
src/pattern_matching/shift_and.rs
src/pattern_matching/ukkonen.rs
src/seq_analysis/gc.rs
src/seq_analysis/orf.rs
src/stats/logprobs.rs
src/utils.rs

Hello,
I ran [clippy](https://github.com/Manishearth/rust-clippy) against rust-bio and implemented the trivial fixes that it raised.
It still passes the tests, feel free to merge if you like it!

Clippy fixes

---

src/alignment/distance.rs
src/data_structures/bitenc.rs
src/data_structures/fmindex.rs

Shorter operators

---

LICENSE.md
README.md
src/data_structures/interval_tree.rs
src/data_structures/mod.rs

Hi,
this is a pull request for basic implementation of interval trees. Currently it supports two operations:
- insert
- find intersection
both of those should run in O(log N). I hope the API (generic with respect to interval bounds) is reasonable, if you have some ideas for improvement I'd be happy to hear about that.

Basic implementation of interval trees based on AVL tree.

---

Cargo.toml
src/alphabets/mod.rs
src/data_structures/bitenc.rs
src/data_structures/bwt.rs
src/data_structures/fmindex.rs
src/data_structures/qgram_index.rs
src/data_structures/rank_select.rs
src/data_structures/smallints.rs
src/lib.rs
src/stats/probs/cdf.rs
src/stats/probs/mod.rs

Switch to new serde compatible with stable rust.

---

src/io/fasta.rs

The current version of the FASTA IndexedReader performs a seek per line, which results in significant overhead since BufReader will seek and invalidate the buffer every time. The attached patch solves this by performing one seek to locate the start of the sequence and then simply reading through and discarding newline characters. It also adds a couple of additional tests that I wrote to make sure that I handled a few cases correctly.
When running a small program that reads through and compares 4 FASTA files, this patch results in the optimized runtime going from 2m50s to just 17s.

Speed up IndexedReader::read by avoiding seeks.

---

src/alignment/pairwise.rs

The size hints provided were being used for actual matrix sizing, with
the result that crashes would occur if the size hints were incorrect.
This commit rewrites the matrix code so it's stored as a single vector
with column-major ordering rather than one per column. Construction cost
is now a single malloc() rather than the 200 that occurred in the
default case and access should also be significantly more cache
efficient.

Fix capacity handling in Smith-Waterman aligner.

---

src/alphabets/dna.rs
src/alphabets/mod.rs
src/alphabets/rna.rs

Primarily added an RNA alphabet so that the project is more complete.
As well, I noted things like 'U' being in the DNA IUPAC alphabet unnecessarily and replaced it with 'Z' (one of many "gap" characters). Did the same with 'T' in the RNA IUPAC alphabet replacing it with 'Z'. I went ahead and reformatted any file I touched with rustfmt too.
I hope to do more work fleshing out this bioinformatics library in the future! (I suspect that because I recently joined a lab doing phylogenetics work I will mostly add features there.)
Does this team have any formal pull request, commit, or contribution guidelines?

Add RNA alphabet (and some nitpicks)

---

src/stats/mod.rs
src/stats/pairhmm.rs

This PR adds an initial implementation for pair HMMs.

Add pair HMM implementation.

---

src/alignment/mod.rs

I accidentally removed the non-htslib cigar string generation.  Restoring.

restore non-htslib cigar string method & tests

---

src/io/bed.rs

These are very common in the wild & currently cause a deserialization error.

allow compact BED files that only have 3 columns

---

src/io/gff.rs

Some GTF/GFF files contains comment lines that starts with #. These lines should be ignored.

Ignore comment lines in GFF/GTF files

---

src/lib.rs
src/stats/bayesian/bayes_factors.rs
src/stats/hmm.rs

Fixes deprecated method warning from nd_array

ndarray subview is now index_axis

---

src/io/fastq.rs

Improve documentation of FastqRead.read method

---

src/io/bed.rs
src/io/gff.rs

Fixing copy-paste error.
This is my first pull request ever so let me know if something is looks odd.

Improve documentation of Records (#221)

---

fuzz/Cargo.toml
fuzz/fuzz_targets/banded_aligner.rs
src/alignment/pairwise/banded.rs
src/alignment/pairwise/mod.rs

Found by a new aligner fuzzer.  Thanks to @sreenathkrishnan for this!

Fixes to aligner edge cases

---

src/io/fasta.rs
src/io/fastq.rs

Closes #243 
In addition, I have added some test cases for functions or corners cases that were missing them. I have also added/extended some docs for a few functions.

Implement fmt::Display for fasta::Record

---

src/seq_analysis/orf.rs

Fixes #291 
Docstring for namespace mentions this is for open reading frames.
'ORF' is used over 'orf' in all public docstrings.
There was block of code which had comments spread out awkwardly. I think the comments must have
been nicely right justified once up a time, but were mangled by rustfmt at some point.
They have been removed and placed as a comment which mentions why VecDeque was used.

Improve documentation for open reading frame

---

src/seq_analysis/gc.rs

Add documentation and doctests for GC content functions. Fixes #293 
I modified the calculation of nth nucleotides per a discussion with @dlaehnemann

Add documentation and fix logic for counting nth bases

---

src/stats/probs/cdf.rs

I have documentation strings for the `CDF` and `Entry` structs and extensive examples for most `CDF` functions. Some might still be missing and I haven't annotated runtime complexity. @johanneskoester , I think this is all your code, initially -- so maybe you want to review this? And if you can find the time, maybe add runtime complexity, as well?

stats::probs::cdf improve docs

---

.rustfmt.toml

Add .rustfmt.toml enabling formatting of code in docs

---

Cargo.toml

This helps us unify versions on some projects. I ran all the unit tests on the intermediate versions & everything passes.

widen version ranges

---

README.md

include `expect()` recommendation in doctest guidelines

---

CHANGELOG.md

Feel free to further adapt this or move it wherever appropriate.

Docathon+ changelog suggestion for version 0.32.0

---

src/stats/pairhmm/homopolypairhmm.rs

Instead of allocating a 2GB transition "table", use a HashMap instead, since only a fraction of the transitions actually happens.

Fix unnecessarily large memory allocation in HomopolyPairHMM #343

---

src/alignment/pairwise/mod.rs

- fix two typos
- add internal links
- fix format (schematics in code blocks; proper new lines)

improve docs of bio::alignment::pairwise

---

src/lib.rs

added BioFerris to rustdoc

---

src/pattern_matching/horspool.rs
src/stats/pairhmm/mod.rs

This will fix #320 completely.

fix cargo doc warnings

---

src/data_structures/fmindex.rs

Hi all,
as proposed on the discord server, I improved the smems computation (from fmd-index). Here three commits:
* smems function now returns also the position on pattern and the smem length (not only the interval on the index)
* now it's possible to compute/return only smems of length >= l
* adds function `all_smems` to compute all smems between the indexed text and a pattern
I'm still testing if everything works as expected but it should be okay. In the meantime, since this is my first contribution to rust-bio (actually it's my first contribution to a rust library), I'd really appreciate any feedback.
Cheers,
Luca

Improve smems computation

---

src/data_structures/interval_tree/array_backed_interval_tree.rs

When testing some code using an ArrayBackedIntervalTree, I discovered that in some circumstances overlapping intervals were not being returned by `find`. Without having too much insight into the implementation, when stepping through the tree construction in a debugger I could see that some internal nodes weren't being touched by the main loop in `index_core`. It looks like in order to match the original implementation in cgranges [here](https://github.com/lh3/cgranges/blob/6da7237627f37ebec6a4e0524a5cf29c28e251be/cpp/IITree.h#L58) a loop condition needed to be changed to include the scenario where the length of the entry array is equal to `2^k`, where k is the rank of the tree nodes to be considered in the iteration.
This PR adjusts that loop condition and adds two tests: a minimal test …

Fix missing indexing in ArrayBackedIntervalTree

---

src/data_structures/smallints.rs

Adds detail to the documentation in smallint.rs to detail time and space complexity.

chore: closes #294: add time/space documentation to smallints.rs

---

src/data_structures/bwt.rs
src/lib.rs

This fixes two broken links, one missing and one outdated. I don't know if the links I replaced are appropriate.

docs: Fix broken BWT links

---

src/alignment/poa.rs

banding for partial order alignments

feat: banded partial order alignments

---

Cargo.toml
fuzz/Cargo.toml

Depend on itertools >=0.8, <0.12

build(deps): Depend on itertools >=0.8, <0.12

---

Cargo.toml

build(deps): bump strum from 0.24.1 0.25.0

---

.github/workflows/conventional-prs.yml
.github/workflows/release-please.yml

Same as: https://github.com/rust-bio/rust-bio-types/pull/61 as mentioned here: https://github.com/rust-bio/rust-bio/pull/566#pullrequestreview-1790263167

ci: allow deps as semantic PR title prefix
