rust-bio/rust-bio

src/lib.rs

example `text` string works without sentinel by coincidence. maybe error message in suffix_array.rs:162 could be more clear that a sentinel is expected on the input text?

text given to suffix_array must have sentinel

---

.travis.yml
README.md
src/alphabets/dna.rs
src/data_structures/bitenc.rs
src/data_structures/fmindex.rs
src/data_structures/rank_select.rs
src/data_structures/smallints.rs

I added nightly to the travis config, but it's allowed to fail. At the very least it'll provide an item for review if a build fails on nightly, but it won't block PRs coming in. I think that second part is important given the recent rand breakage that lasted for over a week before nightly builds were working again for many crates.
The actual code adds feature-flagged serde support for FMDIndex (and RevComp since it's a member of the FMDIndex), BitEnc, RankSelect, and SmallInts. SuffixArray, LCPArray, etc. are already supported because they're just typedefs for Vec\<T: Serialize, Deserialize\>. A few notes:
* In order to support FMDIndex, I needed to add serde for RevComp. Unfortunately, serde doesn't seem to support stack-allocated arrays greater than length 32. I changed the …

More serde support for data structures + nightly on .travis.yml

---

.travis.yml
Cargo.toml
README.md
src/alphabets/mod.rs
src/data_structures/bitenc.rs
src/data_structures/bwt.rs
src/data_structures/fmindex.rs
src/data_structures/qgram_index.rs
src/data_structures/rank_select.rs
src/data_structures/smallints.rs
src/data_structures/suffix_array.rs
src/pattern_matching/bom.rs

The serde support that I PR'd for vec_map has landed in 0.6.0 (https://github.com/contain-rs/vec-map/pull/15).
This PR updates the vec_map dependency to 0.6.0 so that QGramIndex can now have serde on nightly too. I also added the nightly feature flag to the TravisCI config so it'll run tests against both a vanilla nightly and against the nightly feature flag. The vec_map maintainer had a nice suggestion on how to include tests for the serde traits, so I've also added those to all of the data structures.
I think this is probably as much serde support as I'll be able to achieve -- unfortunately serde_macros seems unable to handle some of the type-system-jiggery-pokery that is used in bit_set/bit_vec. Without serde support there, I won't be able to get the alphabet implementations …

Full(ish) serde support + serde coverage on travis + serde compile tests

---

CHANGELOG.md
src/alignment/distance.rs
src/alignment/mod.rs
src/alignment/pairwise.rs
src/alphabets/dna.rs
src/alphabets/mod.rs
src/alphabets/protein.rs
src/io/fasta.rs
src/io/fastq.rs
src/pattern_matching/bndm.rs
src/pattern_matching/bom.rs
src/pattern_matching/myers.rs
src/pattern_matching/shift_and.rs
src/pattern_matching/ukkonen.rs

Refactors various parts of the API to use IntoTextIterator instead of slices. Missing is BWT and SuffixArray related stuff, because this is currently refactored in pull request #47.

Refactor to text iterators

---

src/io/fasta.rs

fasta::IndexedReader was broken for multi-line reads. 
one question on API design: what should the behavior be if the requested stop is greater than the size of the contig?  Here I'm silently truncating, it might be better ot return an error to force the user to fix their code? Thoughts?

fix fasta::IndexedReader for multi-line reads and add unit tests

---

.travis.yml

Updating travis-cargo invocation to avoid spurious nightly build failures.
Note that the CI build will fail until the io::bed test case is resolved, see #66 for a quick fix there.

Fixing nightly travis builds.

---

src/data_structures/interval_tree.rs

Currently we can't actually access the results of IntervalTree::find because the fields on Entry are not public.

make Entry fields public so that clients can read data

---

src/data_structures/interval_tree.rs

This fixes #94.
The error part of the result is currently a String. Should I create an error Enum?
I see I left the line 10 change in the code. I wondered what the Eq/PartialEq should mean, looking at it more carefully I see that it's also derived on Node meaning it will translate into a recursive equality check. Do you want to keep it? If not we can also remove it from the Node struct.

Remove panic! and allow 0-width regions

---

benches/interval_tree.rs

Oops that's embarrassing. Benches are only compiled on a `cargo bench` and it wasn't yet updated for the Result return type. Benchmarking still fails as reported in #90.

Fix bench for updated IntervalTree

---

benches/interval_tree.rs
src/data_structures/interval_tree.rs

I fixed the clippy warnings for the interval_tree. Still many warnings in other code. I can try to fix those as well, but it would basically come down to doing what clippy says and hoping the test suite still runs.

Fix clippy errors interval_tree

---

src/alignment/pairwise.rs

there were some hacks to avoid underflow of the score matrix values. The code didn't generalize to the case where the mismatch penalty was greater than the gap open penalty. This just picks a reasonable minimum score that is still far away from i32:MIN.  Added a test for the case that failed w/ the old code.

avoid underflow errors more systematically & add test

---

Cargo.toml
src/io/gff.rs
src/lib.rs

This does not yet handle comments (see issue #115).

Make gff/gtf parser more robust by using regular expressions for attribute parsing.

---

src/io/bed.rs
src/io/gff.rs
src/io/mod.rs
src/utils/mod.rs

Refactor strand enum. Two unknown strands are no longer equal.

---

src/utils/mod.rs

This PR adds two new method for the Strand enum:
* `Strand::is_unknown` is used for a quick check since `Strand::Unknown` behaves like a Rust's NaN floats.
* `from_char` is for conversions from strand characters used in common formats like BED or GTF.
I also added a new `utils::Error` enum for a failed strand conversion.
Some notes:
* I'm not sure if this is the best place to put the error enum, but there needs to be a way to represent a failed conversion (and I have the impression that there is no generic error types like `ValueError` in Python?). It probably should go somewhere else ...
* I ended up using a `from_char` static method on the enum, but I did consider using a `From` trait or `FromStr`. I didn't end up using `From` since a conversion may fail, and `FromStr` is not used since …

Add 'from_char' and 'is_unknown' static functions for Strand enum

---

src/io/fasta.rs

This pull-request not entirely done, but I wanted your take on it.
This pull-request includes fixing a couple of possible panics when opening .fai files, refactoring IndexedReader, and adding support for reading indexed FASTA sequences using iterators (my original goal). In addition, I noticed some pathological behavior when reading files with long lines, so I capped the size of the internal buffer to 512 bytes for all indexed reads.
I ran into some issues trying to write minimal benchmarks, so instead I wrote some simple tests based on reading through versions of the reference genome used by the 1000 Genomes Project: The vanilla genome, a genome where each chromosome spans one line, and a version where 60 bp lines are bookended by 60 spaces. The code itself can be found here: …

Iterator for fasta::IndexedReader

---

benches/distance.rs

The 'hamming' distance function was changed return a u64 in https://github.com/rust-bio/rust-bio/commit/4d1854680e1ad54a45d8d7ad8fe997b39894559d, but the benchmarks still try to unwrap a Result.

Fix compilation of benches/distance.rs

---

src/io/fasta.rs

This pull request is for a few small issues I noticed in io::fasta.
More specifically, the current implementation of Record::id() returns Some("") if the header is empty, instead of a None. Additionally, the two iterators in io::fasta can potentially return an infinite stream of Err values if an error occurs during iteration. This has been changed so that iteration terminates after the first error, similar to . Finally, the patch adds additional tests, including for the issues described above, and fixes some cosmetic stuff (comments referring to FastQ instead of Fasta and a minor clippy lint).
Cheers

Small fixes to io::fasta

---

src/io/gff.rs

Hello everyone,
This is to continue the initial #132 issue. Many of the things I mentioned there are debatable, but I thought I'd start with the less-debatable ones first :). The current `gff::Record` does not have any `frame_mut` method, which makes its `frame` value unchangeable. This simple fix adds the method so that the value can be changed post-creation.
If this is ok, I'd like to implement the following changes (ordered from less opinionated first):
* Use `char` instead of `String` for the underlying strand type.
* Update gff::Record::new() to accept a tuple of the required values (as the current `new()` method seems practically the same as the derived `default()`).
* Convert the coordinate of `gff::Record` to use `bio::utils::Interval`.
* Use setters for changing the record values …

Add missing `frame_mut` method to gff::Record

---

src/io/gff.rs

According to http://gmod.org/wiki/GFF3#GFF3_Format
"multiple tag=value pairs are separated by semicolons" in the attributes
field.
To be compliant with the specification, the terminator has been changed from `,` to `;` and the test examples have been updated.
Additionally, "multiple attributes of the same type are indicated by
separating the values with the comma." In other words, if an attribute
has multiple values, these values are separated by commas. This feature
is yet not supported...

Changed terminator from ',' to ';' for GFF3.

---

Cargo.toml
src/data_structures/bwt.rs
src/lib.rs

This should give a modest speedup, even more with `simd-accel` or even `avx-accel` feature enabled.

use bytecount for Occ::get

---

src/utils/mod.rs

I'd like to use `Strand` in data types that I use with `HashSet` containers and as `HashMap` keys. Deriving a `Hash` implementation would make this easier.
I definitely see the motivation for the `PartialEq`-only equality operator on `Strand`, and of course these data structures using `Strand` would need custom equality implementations, but a derived `Hash` on `Strand` would avoid the need for an additional, non-derived `Hash` implementation.

Make it easier to use Strand in hashed structs

---

src/alignment/mod.rs

I found myself reading the source to figure out how the Del and Ins alignment operations corresponded to gaps in sequences x and y in pairwise alignments -- I thought it would be helpful to address this directly in the docs.

Clarify which sequence is reference for Del and Ins

---

Cargo.toml
src/io/bed.rs
src/io/fasta.rs
src/io/gff.rs
src/lib.rs
src/stats/probs/mod.rs

fixes #130
@johanneskoester The `csv` crate is still in beta, but everything works with some minor tweaks (and I'm tempted to remove this dep). Will you be okay with this?

Remove rustc-serialize dependency

---

src/stats/probs/mod.rs

* add function to cap LogProb values to probability range
boundary of 1 (which is ln_one() for LogProb) if they
are above 1, but only less then a specified epsilon
This is based on a discussion in the `libprosic` library that depends on `rust-bio`, you can check out [the respective issue](https://github.com/PROSIC/libprosic/pull/20).
@johanneskoester Do you think `cap_numerical_overshoot` is descriptive of what the function does? Are you OK with the implementation and the documentation?

add LogProb::cap_numerical_overshoot() with tests

---

src/alignment/distance.rs

This change produces a minor performance increase.
From https://docs.rs/itertools/0.7.4/itertools/fn.multizip.html
>Prefer izip!() over multizip for the performance benefits of using the standard library .zip(). Prefer multizip if a nameable type is needed.
But since there's only two iterators to zip, I figured using the stdlib was even more straightforward. On my system there's ~2% performance increase on `bench_hamming_dist_equal_str_1000iter`.
I'm not familiar enough with this project to know the conventions for copyright etc - let me know what to do if needed.
Thanks, ben

distance: hamming: Use zip from stdlib rather than itertools' multizip.

---

src/pattern_matching/ukkonen.rs

This should fix #117. I did a comparison with the implementation in "Algorithmen auf Sequenzen" and found that a simple switching of column indices fixes the issue. IMHO, column 1 should be the leftmost (prev) column in the first iteration of the search. Before, it was the other way round.

Fix for #117

---

src/stats/probs/mod.rs

This is necessary, e.g., for using `LogProb` in an `ndarray::Array2`.

Adding trait Zero for the probability types.

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/stats/hmm.rs
src/stats/mod.rs

The implementation is generic enough to allow for both discrete and univariate continuous emission probability distributions.
The implementation also contains the Viterbi, Forward, and Backward algorithm.
~~However, I still need to clarify why the result of the Forward algorithm is not the same as the one from the Backward algorithm in the tests using normal distribution for emission probabilities.~~
Edit: bug fixed

Implementation of Hidden Markov Models

---

src/stats/hmm.rs

The iterators must be constructable for implementing models outside
of rust-bio.

Adding missing constructors on HMM-related types.

---

src/io/fasta.rs

Adds examples to `bio::io::fasta::Reader` to address issues listed in issue #189.

Adding examples to bio::io::fasta::Reader

---

src/stats/bayesian.rs
src/stats/probs/cdf.rs
src/stats/probs/mod.rs
src/utils/fastexp.rs
src/utils/mod.rs

Use the approximation for LogProbs. This should provide speedups up to 5x, depending on the function.

Implement the fast but accurate approximation of exp presented by Kopcynski 2017.

---

benches/pairhmm.rs
src/data_structures/rank_select.rs
src/stats/hmm.rs
src/stats/pairhmm.rs
src/stats/probs/mod.rs

* Omit superfluous parts of the matrix.
* Skip unnecessary ln or exp operations.
* Avoid repeated indexing into vectors.
This should improve pairHMM runtime by up to 40% (in the semiglobal case) and about 20% in the global case.

Optimize pairHMM implementation

---

CHANGELOG.md
src/data_structures/bwt.rs
src/io/fasta.rs
src/io/fastq.rs

I added the traits `FQRead` and `FARead` to the `FastqReader` and `FastaReader` modules respectively. The contain the `read` method which allows to use them when the input type is not clear at compile time, for example if the user could either supply a `.fq` file or a `.fq.gz` file. These would result in different flavors of the generic `<R>` of the reader and in turn make it complicated to use a pattern like this:
```
let path = "reads.fq.gz";
let mut fq_reader: Box<FQRead> = match path.ends_with(".gz") {
true => Box::new(Reader::new(io::BufReader::new(FASTQ_FILE))),
false => Box::new(Reader::new(FASTQ_FILE)),
};
```
Right now, this is only implemented for the `read` method. It would be nice, to also have this for the `records` method, but that turned out to be not that straight forward …

Reader traits

---

src/seq_analysis/gc.rs

I'm new to Rust and saw this test was missing so I figured it was an easy way to start getting involved. I was also thinking on expanding the `seq_analysis` module with additional quality metric functions e.g. calculating base quality and content by position within a read?

Add test for calculating GC content

---

src/data_structures/fmindex.rs

This PR updates the docs for `FMIndex::new`, to reflect the current API.

update docs for FMIndex::new

---

src/io/fasta.rs
src/io/fastq.rs

* No longer allocate a header string but reuse the same buffer
as the sep_line. This buffer is now renamed to line_buf.
* Avoids creating two iterators when extracting header fields.

Improve performance of FASTQ reader

---

src/io/fasta.rs

Updated the documentation for the `FastaRead.read` method. In particular it is now clear that there are no more records when the record is empty.
I tried to follow the guidelines at https://rust-lang-nursery.github.io/api-guidelines/documentation.html as much as possible whilst ammending the documentation. As a consequence, I tweaked the the example to use `?` instead of `unwrap()`.  I also made the declaration of `fasta_file` visible in the example, because the assertions make much more sense with a bit of context.

Improve documentation of FastaRead.read method

---

src/alphabets/dna.rs
src/alphabets/rna.rs

These will never change size so its more idiomatic to use an array.

Use array rather than Vec for COMPLEMENT tables

---

src/alignment/pairwise/banded.rs
src/alignment/pairwise/mod.rs
src/data_structures/annot_map.rs
src/data_structures/interval_tree.rs
src/data_structures/smallints.rs
src/io/bed.rs
src/io/gff.rs
src/pattern_matching/myers/builder.rs
src/pattern_matching/myers/mod.rs
src/pattern_matching/myers/traceback.rs
src/pattern_matching/pssm/dnamotif.rs
src/pattern_matching/pssm/mod.rs
src/pattern_matching/pssm/protmotif.rs
src/pattern_matching/shift_and.rs
src/pattern_matching/ukkonen.rs
src/seq_analysis/orf.rs
src/stats/pairhmm.rs
src/utils/fastexp.rs

* fix all redundant field name issues
* fix redunant closures
* fix unused lifetimes
* use inclusive range syntax
* use is_empty()
* remove useless into_iter
* fix inferable lifetimes
* use rustfmt::cfg rather than cfg_attr
* fix long literal warnings
* fix more range inclusive warnings
* fix pass by reference warnings

Fix various clippy warnings

---

Cargo.toml

The derive-new crate was added in c56eaa53a17f6e2d6d072fe54a7cca42d83893e9, as part of PR #224, but its use was dropped in subsequent commits.

Remove unused crate in Cargo.toml

---

src/data_structures/rank_select.rs

select_0(0) and select_1(0) now always return None.
Previously it would sometimes return 0.
Fixes #226

fix select_* when rank is 0.

---

Cargo.toml

Use runtime dispatch SIMD for bytecount to get binaries that automatically use the best instructions.

update some deps to stay current.

---

src/data_structures/fmindex.rs

This stops LF-mapping when a symbol in the pattern couldn't be mapped to an interval in 'F'.
Previously large patterns would continue to be LF-mapped even after a symbol was found not to occur.

Terminate backwards search if a symbol isn't found.

---

src/data_structures/suffix_array.rs
src/pattern_matching/myers/common_tests.rs

`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.

Use `slice::iter` instead of `into_iter` to avoid future breakage

---

src/io/fastq.rs

- Fixes the bug in `fastq::Record` `fmt::Display` implementation [closes #241] 
- Adds tests to cover missing corner cases and untested functions
- Adds doc example for `fastq::Reader::record()`
I am not incredibly experienced with Rust yet so, please feel free to point out places where I could do things better.  
Also, some feedback on the doc I added, and it's example would be great.

Fix fastq record Display implementation and add more tests

---

src/io/fasta.rs

There is no "hard" specification for FASTA, but most applications adhere to ">ID{SPACE}DESCRIPTION"; however, some do not use {SPACE} but a different whitespace character such as {TAB}. The question now is whether to rely on the user to supply FASTA files which use space (and only space) as separator between id and description or to allow a larger set of whitespaces.
This PR does the latter:
Instead of splitting at the first _space_, split at the first [whitespace](https://en.wikipedia.org/w/index.php?title=Whitespace_character#Unicode) as given by rust's[ `char::is_whitespace`](https://doc.rust-lang.org/std/primitive.char.html#method.is_whitespace) (or, alternatively [`char::is_ascii_whitespace`](https://doc.rust-lang.org/std/primitive.char.html#method.is_ascii_whitespace)).
(Note that …

Allow any whitespace (w.r.t unicode) between id and description in FASTA headers

---

Cargo.toml
tests/data_structures/mod.rs
tests/data_structures/rank_select.rs
tests/mod.rs

This PR adds proptests for the RankSelect data structure.
Two naive data structures are added for doing Rank and Select calculations. They are both generic over the sequence type so they can handle arbitary alphabets. In the case of this PR we have tests for a `bool` alphabet as RankSelect in rust-bio is currently for bitvecs.

Proptest for RankSelect

---

Cargo.toml

This allows users of rust-htslib to upgrade to syn/quote 1.0, and eliminate a dependency on syn 0.15 which tends to take a lot of compile time.

expand version compatibiltiy of snafu

---

src/data_structures/bit_tree.rs

Nightly (1.43) was complaining about this.

Use unique parameter names in trait method definition.

---

.gitignore
src/io/fastq.rs

Reverts rust-bio/rust-bio#255
Issue found by @mbhall88:
@johanneskoester I think the merge you performed didn't really merge how you would hope/expect. For instance, the `read` method on `fastq` has mixed the new (line-wrapped-handling) logic with the old logic so that now calling `read` will read two lines - one in the new and another in the old way.
https://github.com/rust-bio/rust-bio/blob/e540963816851c54c63a5cff5049b961ef32e030/src/io/fastq.rs#L135-L202
_Originally posted by @mbhall88 in https://github.com/rust-bio/rust-bio/pull/222#issuecomment-596074611_

Revert "Handle wrapped fastq files"

---

src/seq_analysis/orf.rs

This PR adds tests to cover various orf finding scenarios. I added `#[derive(Debug, PartialEq)]` to the `Orf` struct for the tests, but happy to take another approach if this isn't idiomatic or preferred.

Add tests for orf finding algorithm

---

src/stats/pairhmm.rs

Code logic for the case where no gap extensions are allowed was flawed (basically restricted the DP to its diagonal when a cone should be considered instead). This PR fixes this by considering all columns of y, which will be a performance hit for cases where no gap extension is allowed.
This PR also adds more stringent tests, using the (manually defined) probability of the most likely state path as an estimate.

PHMM: Bugfix for no gap extension case and more stringent tests.

---

src/stats/pairhmm/homopolypairhmm.rs
src/stats/pairhmm/pairhmm.rs

- This PR moves caching of the probabilities defined by the `GapParameters` trait into the `new` constructor of `PairHMM` such that a `PairHMM` instance can be re-used, assuming that the `GapParameters` do not change between two calls of `prob_related` (which is -- in most use-cases -- likely true).
- The `gap_params` argument to `prob_related` also required the trait `StartEndGapParams` to be implemented, so this has been moved to `alignment_mode`. 
- This PR breaks existing code which uses `PairHMM`.
Before:
```rust
let mut pair_hmm = PairHMM::new();
let p = pair_hmm.prob_related(&gap_params, &emission_params, None);
```
After:
```rust
let mut pair_hmm = PairHMM::new(&gap_params);
let p = pair_hmm.prob_related(&emission_params, &AlignmentMode::Global, None);
```
where `AlignmentMode` …

Move caching of GapParameters to `PairHMM::new`, adapt tests accordingly

---

Cargo.toml
benches/distance.rs
src/alignment/distance.rs

Hello everyone, I am working on new SIMD-accelerated Hamming and Levenshtein distance functions that are added into the `alignment::distance::simd` module. This work is based on issue/proposal #268.

Integrating SIMD-accelerated edit distance routines from the `triple_accel` library into the `alignment::distance` module

---

README.md
src/alignment/distance.rs
src/alignment/sparse.rs
src/data_structures/bwt.rs
src/data_structures/fmindex.rs
src/data_structures/interval_tree/array_backed_interval_tree.rs
src/data_structures/qgram_index.rs
src/data_structures/suffix_array.rs
src/io/bed.rs
src/io/fasta.rs
src/io/fastq.rs
src/io/gff.rs
src/lib.rs
src/scores/blosum62.rs
src/scores/pam120.rs
src/scores/pam200.rs
src/scores/pam250.rs
src/scores/pam40.rs
src/stats/hmm/mod.rs
src/stats/pairhmm/mod.rs
src/stats/pairhmm/pairhmm.rs

In preparation of the docathon, this is an attempt at making the rust-bio website obsolete and moving all documentation to the README.md and the module documentation on docs.rs
Hopefully, this will make both using the docs and maintaining them a bit easier.
Also: Update FASTQ parsing examples to a pre-allocated record, which is a more efficient method.

Integrate essential info from website into README.md and rendered docs.

---

src/data_structures/interval_tree/array_backed_interval_tree.rs

The example given in `ArrayBackedIntervalTree` had errors. Fixed those ;)

Fix doctest/example for ArrayBackedIntervalTree

---

src/data_structures/interval_tree/array_backed_interval_tree.rs
src/io/fastq.rs
src/lib.rs

Some doctests were failing (because of unresolved imports, wrong variable references, ...) -- they shouldn't fail anymore, now

Fix doctests

---

.github/workflows/rust.yml
Cargo.toml
src/data_structures/interval_tree/array_backed_interval_tree.rs
src/io/fasta.rs
src/io/fastq.rs
src/lib.rs

While updating #222 I noticed that 3 tests are failing on master, despite CI passing. Seems like `tarpaulin` is not erroring for these tests...
This PR adds an extra `testing` job that runs tests on Rust stable for Ubuntu, macOS and Windows, and beta on Ubuntu.
I also switched the coverage job to use `nightly` and run with `--all-features`, to check coverage as much as possible (`tarpaulin` runs only on Linux, and `packed_simd` requires `nightly`).
Finally, I saw [actions-rs/tarpaulin](https://github.com/actions-rs/tarpaulin/) is [starting to recommend](https://github.com/actions-rs/tarpaulin/issues/6) using `actions-rs/install` instead, so I already adapted the `coverage` job to do this.

Split coverage and testing jobs on CI

---

.pre-commit-config.yaml

In order to reduce the number of "fmt" commits (and hence reduce the number of CI triggers), this PR adds a `.pre-commit-config.yaml` for use with [pre-commit](https://pre-commit.com/).
In order to use this:
1. install `pre-commit` (see [pre-commit.com/#installation)](https://pre-commit.com/#installation)
2. run `pre-commit install` in the rust-bio base dir
and henceforth every time you commit, *changes* will be formatted with rustftm and checked with cargo check!

Add rustfmt and cargo check pre-commit hooks

---

src/alphabets/dna.rs
src/alphabets/mod.rs
src/alphabets/rna.rs

This PR adds doctests for all public functions and methods in the alphabets module.
Additionally, it adds module tests for `dna` alphabets, which test if methods of `Alphabet` behave as expected when working with `dna`.

Alphabets documentation

---

src/data_structures/bitenc.rs

This PR implements the traits Hash, Eq and PartialEq für die BitEnc struct.
These are required for including a BitEnc object into a HashMap and for (de)serializing using serde.

Additional traits for BitEnc

---

Cargo.toml

The previous version of `triple_accel` looks at the `debug_assertions` flag to determine whether to print debug output. This was potentially annoying for dev builds/tests, so this was swapped out for a separate feature flag that is off by default. This pull request just updates the version of `triple_accel` so that debug output is not printed by default. Debug output can still be enabled by passing the `debug` feature flag to `triple_accel`.

Updated debug feature flag so debug output is not printed by default

---

benches/pairhmm.rs

This PR updates the `pairhmm` benchmark to conform to `PairHMM` constructor and `prob_related` function changes introduced in #267

Fix pairhmm bench compilation

---

src/data_structures/annot_map.rs

Reorganizes and cleans up `data_structures::annot_map` docs as part of #283

Improve docs: data_structures::annot_map

---

src/seq_analysis/gc.rs

Fixes #337 (but still uses f32, not f64, since that'd change the function's signature)

Quick fix floating point error in gcn_content

---

src/io/fasta.rs

This PR adds the actual sequence name that was not found to the error message of the fasta reader.

Improve error message for fasta reader

---

src/lib.rs

Without the `$`, FM-index cannot works.

Quick fix, completion example.

---

src/io/bed.rs

This PR adds support for reading compact bed files. It removes the manual deserialization of `BedRecordCsv` in favor of using serde's `#[serde(default)]` [field attribute](https://serde.rs/field-attrs.html#default) for `aux`, which will default to an empty vector if the field is missing.

Support reading compact bed

---

Cargo.toml

`triple_accel` version 0.3.2 causes `bio` fail to compile with `cargo 1.48.0-nightly (875e01232 2020-09-08)`. This has been fixed in the latest [v0.3.4 on 2020-09-17](https://crates.io/crates/triple_accel/0.3.4) thanks to @Daniel-Liu-c0deb0t : https://github.com/Daniel-Liu-c0deb0t/triple_accel/issues/3

update triple_accel version

---

README.md

Now that we are permanently using the Discord server (which was initially created for the 2020 Docathon), we might as well add the invite link to the main README.md to make it more accessible.

add Discord server to Contribution section of README.md

---

src/alphabets/mod.rs

Fairly minor change, but this makes it possible to compare two alphabets for equality. This assumes two alphabets are equal if their BitSets are equal.

Add PartialEq and Debug impls for Alphabet.

---

src/io/gff.rs

Implements [from_str](https://doc.rust-lang.org/std/str/trait.FromStr.html) for `GffType`, useful to accept an input from a CLI or something and get the appropriate type.

Add from_str impl for gff.

---

src/alphabets/mod.rs

Adds basic set operations to the alphabet. Also adds upper and lower english alphabets. These together are useful for things like taking the built in protein alphabet, and filtering it to be only upper to reduce the alpha size overall.
Also somewhat newer to rust, so if there's some better idioms to follow, happy to do so.

Adds niceties for taking union/intersect/difference on alphabets.

---

src/pattern_matching/myers/long.rs
src/pattern_matching/myers/simple.rs
src/pattern_matching/myers/traceback.rs
src/utils/fastexp.rs

There's two uses of `unsafe` that aren't necessary for performance
or functionality:
- using a union to convert between raw bits in a f64 floating point
format and f64 itself, because there's the [safe `f64::from_bits`
function in std](https://doc.rust-lang.org/std/primitive.f64.html#method.from_bits)
- using from_raw_parts to build a slice `&[T]` from a single &T, because
there's [the safe `std::slice::from_ref` function](https://doc.rust-lang.org/std/slice/fn.from_ref.html)
The latter flags a minor safety issue: the
ShortTracebackHandler::column_slice method had an incorrect lifetime
in its return value. It was incorrectly suggesting that the returned
slice lived for longer than the `self` value. In particular, code
could write something like (in pseudo-Rust, with named lifetimes of …

Remove some uses of unsafe from Myers pattern matching and fastexp

---

README.md

This PR adds `pre-commit` instructions from #312 to the README Contribute section so that everyone can catch formatting issues before pushing.

Update README to include pre-commit instructions

---

src/alignment/pairwise/mod.rs

Currently, the pairwise alignment docs provide examples of custom scoring functions. This PR adds an example of how to use a predefined substitution matrix such as BLOSUM62.

Add pairwise align doc example with subst matrix

---

README.md

Currently clicking on the Actions build badge opens a page containing only the badge image. This change links the badge to the Actions page.

Link README Actions badge to Actions page

---

src/pattern_matching/shift_and.rs

This changes the order of addition and subtraction to avoid a subtract
with overflow panic that occurred when the pattern was at the beginning
of the text.
Fixes #416.
Edit: this also adds a test case for the issue.

Fix pattern matching subtract with overflow panic

---

src/scores/blosum62.rs
src/scores/pam120.rs
src/scores/pam200.rs
src/scores/pam250.rs
src/scores/pam40.rs

This PR adds documentation for BLOSUM62, PAM40, PAM120, PAM200, and PAM250 scoring functions.

Add substitution matrix scoring documentation

---

CHANGELOG.md
src/io/fasta.rs
src/io/gff.rs

This PR improves (some) documentation for the FASTA index module [closes #422 ].
It (may) also makes some private methods and struct public [#421]. (I will wait to see what the discussion on #421 concludes as to whether to add this to the PR)

Improve fasta::Index useability

---

Cargo.toml

Currently users of the bio 0.34 will have rand 0.7.3 as a dependency.  This change
allows the rand dependency to advance to 0.8.3.  It would be great if a release could 
be made with this change.

update crates so that users can use rand version 0.8.3

---

src/data_structures/suffix_array.rs

Just a quick fix of for `#[warn(non_fmt_panic)]`. Looks like the `format!` macro should be avoided inside the `assert!` as shown [here](https://doc.rust-lang.org/std/macro.assert.html#custom-messages) in the example for custom error messages with `assert!`.

Fix compiler warning when running tests

---

src/io/fastq.rs

I found this bug while writing tests for this: https://github.com/rust-bio/rust-bio/pull/433. I felt that this was somewhat urgent and the fix shouldn't be tied to my PR.
In the current code at `src/io/fastq.rs:252` the code loops while the line does not start with `+`, adds the contents of the line to the sequence, then reads the next line and increments `lines_read`:
```Rust
while !self.line_buffer.starts_with('+') {
record.seq.push_str(&self.line_buffer.trim_end());
self.line_buffer.clear();
self.reader.read_line(&mut self.line_buffer)?;
lines_read += 1;
}
```
The problem is that at the end of a file `read_line` will simply read an empty string. The empty string never starts with `+` so this will loop forever, even once you have reached the end of a file. This is not ideal and can …

fix edge case where FastX parser can loop infinitely

---

Cargo.toml
benches/fasta_buffer_size.rs
src/io/fasta.rs
src/io/fastq.rs

This pull request try to solve issue #258.
I add constructor `from_file_with_capacity`, `with_capacity`, `from_bufreader` to `Reader` and `with_capacity`, `to_file_with_capacity` to `Writer`.
I also add a benchmark to demonstrate, this constructor is more efficient than build a `BufReader` and give it to `new` constructor. Benchmark run on my XPS13 with SSD.
```
test fasta_buffer::default           ... bench:     151,396 ns/iter (+/- 1,561)
test fasta_buffer::wrapped_default   ... bench:     145,718 ns/iter (+/- 2,595)
test fasta_buffer::capacity_default  ... bench:     139,736 ns/iter (+/- 27,226)
test fasta_buffer::bufreader_default ... bench:     138,331 ns/iter (+/- 2,336)
test fasta_buffer::wrapped_32768     ... bench:     147,414 ns/iter (+/- 1,752)
test fasta_buffer::capacity_32768 …
```

Allow user to control size of reading and writting buffer

---

Cargo.toml
src/stats/hmm/mod.rs

Some improvements related to Hidden-Markov Model Module:
* Implementation of Baum-Welch algorithm for Discrete HMM;
* Creation of a trainable Discrete Emission Module with implicit end state;
* Add tests for Baum-Welch algorithm.

feat: Baum-Welch algorithm for Discrete HMM

---

src/data_structures/bwt.rs
src/data_structures/fmindex.rs
src/data_structures/suffix_array.rs

The sampled suffix array implementation has some issues (closes #70 and closes #446) from like 2016, so the code was commented out and the issues were never fixed... until now.
The issue is that wrong positions are returned when doing a last to front lookup that leads to a sentinel in the FM-index. This issue only happens when there are multiple sentinels. I think is due to how SAIS ranks the sentinels so they are different despite being the same character `$` so the final result will not be a fully lexicographical sorting. The FM-index doesn't know this so you get wrong results when looking up a sentinel in `occ` or `less` for the last to front mapping. Normally, you wouldn't look up sentinels so this issue wouldn't come up, but with a sampled suffix array, sometimes you need to follow …

fix: sampled suffix array

---

src/data_structures/bwt.rs
src/data_structures/fmindex.rs
src/data_structures/suffix_array.rs

Occ wastes a lot of memory because it reserves memory for all alphabets up to the one with the max rank. Without compression, rank is based on the ASCII value, so this means that a small alphabet like DNA nucleotides would take ~10x more memory than necessary. The FMD index also does not support compressed alphabets, so there is no easy way to sidestep this issue. The fix is simple: transpose the Occ vector so that the first dimension is the alphabet and the second dimension is the sampled Occ values. Then, for characters not in the alphabet, the second dimension can simply be empty, and no space would be wasted. This should massively improve speed and memory usage.
This will need to be rebased after #447 is merged.

fix: One Simple Trick to significantly improve the speed and memory usage of Occ

---

src/alphabets/protein.rs

Implements the IUPAC alphabet for proteins as requested here: https://github.com/rust-bio/rust-bio/issues/435.

feat: adds iupac amino acid alpha

---

src/data_structures/fmindex.rs

An early-return check for empty intervals during the backward search actually checked for a length of 1, which caused the search to return incorrect suffix array intervals. Fixes #454.

fix: backward search on FM-Index (#454)

---

Cargo.toml

Allow update of strum to latest version.
Nothing actually depends on fnv.

chore: widen range for strum, remove fnv.

---

benches/fmindex.rs

This was broken by eb9d378c70bc43d1dcf477e48cb167802799a546.
Having compilation broken is an annoyence when one attempts to run
`cargo check --all-targets`.

test: fix compilation for fmindex benchmark.

---

CHANGELOG.md
src/io/bed.rs

Added code to ignore commented lines in a bed file and also added a simple test function. I think this resolves https://github.com/rust-bio/rust-bio/issues/473.

fix: added code to ignore commented lines in a bed file 

---

CHANGELOG.md

Currently the CHANGELOG is out of order and has inconsistent use of headers i.e. `#` vs. `##` vs. `###`. This PR fixes the ordering and updates headers to the format used by the release bot (`##` for minor, `###` for patch).

docs: reorder CHANGELOG and fix headers

---

src/data_structures/qgram_index.rs

I've added some more documentation and clarifying tests to `QGramIndex`,
so that the implementation is more clear without looking at the code.
I found one small bug: q-grams of value `0` (i.e. `AAA`) wouldn't be
filtered by `max_count`. I've added a test that would fail if the
`.skip(1)` was still there.
The size of the `pos` vector was always `|text|`, but it's sufficient to
only allocate memory for the number of unfiltered q-grams. Please verify
this. I've added a `text="AAAAA"`, `pattern="AAA"` test that should show
that things are still working.

fix: Make QGramIndex use less memory; add docs; fix bug

---

.github/workflows/rust.yml
README.md
src/alphabets/mod.rs

For k exactly equal to 32 (or generally when the assertion above has exact
equality), the `1<<(q*bits)` overflows, which is undefined in rust. This PR
makes it defined behaviour.

fix: overflow in `qgrams` for k=32

---

src/stats/pairhmm/homopolypairhmm.rs

`build_transition_table` now expects something that implements the trait `BaseSpecificHopParameters` instead of `HopParameters`, since the latter can be expressed as the first (i.e. there's a default impl of `BaseSpecificHopParameters` for anything that implements `HopParameters` which just uses the base-agnostic homopolymer run start / extend probabilities)

feat!: base specific hop parameters in homopoly-pair-hmm

---

src/alignment/pairwise/mod.rs
src/alphabets/mod.rs
src/data_structures/fmindex.rs
src/data_structures/qgram_index.rs
src/io/fasta.rs
src/io/fastq.rs
src/io/gff.rs
src/pattern_matching/pssm/errors.rs
src/seq_analysis/orf.rs
src/stats/hmm/errors.rs
src/stats/hmm/mod.rs
src/stats/probs/mod.rs
src/utils/interval/errors.rs

Mostly things that could be #[derive(Eq)] but weren't.

chore: Fix lints from clippy 1.63.

---

.github/workflows/rust.yml

Pin the version of indexmap (transitive dependency) to 1.8.2, the last
version before they switched to edition 2021, which requires rust 1.56.

chore: Fix MSRV build.

---

CHANGELOG.md
Cargo.toml
src/pattern_matching/pssm/mod.rs
src/stats/probs/adaptive_integration.rs
src/stats/probs/mod.rs

Figure it'll need to change eventually.

feat!: Update `strum` and `ordered-float` dependencies and change From<LogProb> into TryFrom<LogProb> for NotNan<f64>.

---

Cargo.toml

They didn't actually make breaking changes.
Also, due to a disagreement between the common meaning of semver for
pre-1.0 releases and how the release-please bot works, someone needs to
merge a commit with this line in it, so it might as well be this one:
Release-As: 0.42.0

chore: widen range on statrs

---

src/seq_analysis/orf.rs

When testing the Rust Bio ORF finder against this [Rosalind problem](https://rosalind.info/problems/orf/), I discovered that the `MTPRLGLESLLE` ORF was being missed! This was because it's an ORF nested within the `MGMTPRLGLESLLE` ORF in the same frame and the old algorithm did a single pass and only recorded one ORF starting position at a time.
The new algorithm still performs only a single pass, but can build up a list of alternative start positions before a stop is encountered.
I've added some more comments in this thread to justify my changes and wrote a new test for this nested case. I've switched to using this fork for my [syn-zeug](https://github.com/Sheffield-iGEM/syn-zeug) project, but I'd love to see this merged and move back to using upstream!

feat: detect nested ORFs

---

src/alphabets/dna.rs
src/alphabets/rna.rs

This speeds up computing the complement on a long string by ~2.3x. Not sure why rust doesn't inline such a trivial function on its own.
I didn't manage to compile your benchmarks, hence I can only point to the results from my [own project](https://github.com/kloetzl/libdna/blob/master/rust/benches/Brevcomp.rs).
> dna4_revcomp            time:   [688.18 µs 690.09 µs 692.27 µs]                         
> dnax_revcomp            time:   [3.0615 ms 3.0705 ms 3.0815 ms]                          
> 
> rust-bio                time:   [12.029 ms 12.105 ms 12.212 ms]                     
> rust-bio inlined        time:   [5.0742 ms 5.0901 ms 5.1087 ms]                              
There is still a small overhead of Rust over C. I think Rust repeatedly checks that `a as usize` is a valid index in …

perf: mark dna::complement as inline

---

src/lib.rs

I'm not sure this is the right way, but it should ensure users of rust-bio
can drop the direct dependency of bio_types and import via
`use bio::bio_types` instead
Fixes #516

feat: add `pub use bio_types` to lib.rs

---

src/alignment/poa.rs

As issue #443 describes, POA graph is not correct when a sequence is added with an insertion or a mismatch at the start. 
I tried to resolve this issue by allowing the backtrack to reach (0,0) of the traceback matrix instead of stopping at an edge.
Then I added code for the cases when the Alignment operation matches with Match(None) and Ins(None).
Fixes https://github.com/rust-bio/rust-bio/issues/443

fix: edge cases on partial order alignment

---

src/alignment/poa.rs

There was no function available in code to obtain a consensus sequence from the poa graph.
I added this functionality by writing a simple function which returns the sequence with the highest weighted edges.
Fixes #246.

feat: Consensus sequence from partial order alignment graph

---

.github/workflows/rust.yml
Cargo.toml
README.md
src/alignment/distance.rs

Probably, it is better to use the implementation of the Ukkonen algorithm from ```editdistancek```.
Before:
```
test bench_levenshtein_dist_diverse_str              ... bench: 113,214,418 ns/iter (+/- 781,509)
test bench_levenshtein_dist_equal_str                ... bench:  91,783,885 ns/iter (+/- 183,007)
test bench_levenshtein_dist_worst_str                ... bench:  91,866,787 ns/iter (+/- 1,736,995)
test bench_simd_bounded_levenshtein_dist_diverse_str ... bench:  41,695,427 ns/iter (+/- 1,917,682)
test bench_simd_bounded_levenshtein_dist_equal_str   ... bench:  41,640,232 ns/iter (+/- 2,047,975)
test bench_simd_bounded_levenshtein_dist_worst_str   ... bench:  41,474,403 ns/iter (+/- 3,183,653)
test bench_simd_levenshtein_dist_diverse_str         ... bench:  54,980,802 ns/iter (+/- …
```

perf: improve alignment::distance::levenshtein and alignment::distance::bounded_levenshtein on strrings where distance is small

---

.github/dependabot.yml

for conventional commits, see:
https://www.conventionalcommits.org/en/v1.0.0/
for a good cheat sheet, see:
https://kapeli.com/cheat_sheets/Conventional_Commits.docset/Contents/Resources/Documents/index

fix: make dependabot commit message follow conventional commits

---

src/lib.rs

Wildcard version specifications are considered bad practice.
`use` can be used to import crate items since Rust edition 2018.

docs: don't use wildcard version, replace 'extern crate' with 'use'

---

src/alignment/poa.rs

Saves the scores only in the band instead of the whole matrix when using banded poa.
Also fixes global_banded function not skipping to start of the band.
And cleans up test_edge_cases.

feat: memory efficient banded poa

---

.github/workflows/rust.yml
README.md

This is because our current simd dependency has become incompatible with nightly rust.

chore: temporarily disable coverage estimation until simd support has arrived in the stable rust stdlib

---

Cargo.toml

Closes #556 as I was able to reproduce the build error with `0.14` reported by @jakobnissen

fix: minimum ndarray version is 0.15

---

Cargo.toml
src/lib.rs
src/stats/bayesian/model.rs

getset is no longer recommended by its maintainer: https://github.com/jbaublitz/getset/pull/87#issuecomment-1167658416
& is thus unlikely to update to `syn 2`

refactor: remove getset

---

src/io/gff.rs

This PR does some refactoring for `io::gff::Record::frame`. The [docs on gmod](http://gmod.org/wiki/GFF3#GFF3_Format) specifically mention the column `phase` not to be confused with `frame` which is currently the case in the bio crate. I also used the chance to add a better typing to the field as an `Option<u8>` as `Phase` is much nicer to work with than a plain String.
Beware that this is potentially a breaking change although I am not sure this change really qualifies for a new major release of rust-bio.

refactor!: Refactor misleadingly named method io::gff::Record::frame to phase and improve typing

---

src/alignment/distance.rs
src/alignment/pairwise/banded.rs
src/alignment/pairwise/mod.rs
src/alignment/poa.rs
src/alignment/sparse.rs
src/data_structures/annot_map.rs
src/data_structures/bwt.rs
src/data_structures/fmindex.rs
src/data_structures/interval_tree/array_backed_interval_tree.rs
src/data_structures/interval_tree/avl_interval_tree.rs
src/data_structures/qgram_index.rs
src/data_structures/rank_select.rs
src/data_structures/suffix_array.rs
src/data_structures/wavelet_matrix.rs
src/io/bed.rs
src/io/fasta.rs
src/pattern_matching/myers/long.rs
src/pattern_matching/myers/mod.rs
src/pattern_matching/pssm/dnamotif.rs
src/seq_analysis/orf.rs
src/stats/hmm/mod.rs
src/stats/pairhmm/pairhmm.rs
tests/data_structures/rank_select.rs

Fixes all but one clippy warning throughout the repo.
Unfortunately, this means changing a lot of files, though luckily all changes are confined to only a few lines.
The only clippy warning left is the one complaining that the `pairhmm` module has a child called `pairhmm`. I didn't want to `allow` the warning, and changing the module name is not something I wanted to make a decision about.
I considered splitting this PR up on a per module basis in order to potentially make it easier to merge, but I thought I'd start off like this. Each commit only changes a single file and only fixes a single clippy warning, so it should be pretty simple to cherry pick.

fix: Fix clippy warnings

---

src/pattern_matching/myers/simple.rs

Replace two unsafe lines with the equivalent safe lines commented out just above.
The unsafe lines were both unnecessary and allowed the user to cause UB from safe Rust.
See full description in #581

fix: Remove unnecessary and unsound use of unsafe

---

src/data_structures/suffix_array.rs

Hi, I noticed that although SAIS algorithm is general enough for larger integer alphabets, there is no way to use it on these alphabets outside rust-bio crate. This pull request fixes it.
Maybe there is better way how to fix it, so if there is demand for that, somebody more experienced could help me with the design and I could implement that.

feat: added public function for construction of suffix array from integer alphabets

---

src/io/gff.rs

This PR adds a missing method to access the phase of a gff record.

fix: Add missing method to access phase of gff record

---

src/alignment/poa.rs

The current POA implementation gives rise to reverse edges when insertions are made before the head node, this fixes it.
Fixes https://github.com/rust-bio/rust-bio/issues/549.
Fixes https://github.com/rust-bio/rust-bio/issues/572.

fix: POA reverse edge fix

---

src/io/gff.rs

Implements `From<Option<u8>>` and `TryInto<Option<u8>>` for `bio::io::gff` to make handling `Option<u8>` easier.

feat: Implementing From and TryInto for Phase

---

src/data_structures/suffix_array.rs
src/io/gff.rs
src/pattern_matching/pssm/dnamotif.rs
src/pattern_matching/pssm/mod.rs
src/pattern_matching/pssm/protmotif.rs

This PR enables the creation of a position-specific scoring matrix from inputs with ambiguous monomers, eg, DNA sequences containing N bases.
There are two use cases for this:
- some sequencing technologies emit N bases, which would produce an error if used as an input in the current code
- this serves as a [lossy] deserialization technique for the PSSM representation produced by `degenerate_consensus`

feat: position-specific scoring matrix: support inputs with ambiguous monomers in from_seqs

---

benches/fmindex.rs
src/alphabets/mod.rs

This adds a new `RevQGrams` iterator created from `RankTransform::rev_qgrams` that iterates over the qgrams of a `DoubleEndedIterator` in reverse.
It also implements `size_hint` and `ExactSizeIterator` for both `QGrams` and `RevQGrams`, and does some minor cleanup along the way.
Note that I did not implement `DoubleEndedIterator` for `QGrams`, since they need to guarantee that mixing iteration from the left and right produces the same sequence of elements, which would not be the case without extra work.
I've added tests for the new features.

feat: Reverse qgrams iterator

---

Cargo.toml
benches/fasta_buffer_size.rs
benches/fastx.rs
fuzz/Cargo.toml
src/data_structures/suffix_array.rs

- Remove the unused dependency `rand`, keep the dev dependency
- Remove the unused dependency `itertools` from `fuzz`
- Change `rand::distributions` to `rand::distr`
- Change `rand::thread_rng()` to `rand::rng()`
- Change `gen_range` to `random_range`

build(deps): Remove unused dependency `rand`

---

src/alignment/pairwise/banded.rs
src/alignment/pairwise/mod.rs
src/data_structures/qgram_index.rs
src/data_structures/suffix_array.rs
src/pattern_matching/myers/long.rs
src/pattern_matching/myers/simple.rs
src/pattern_matching/pssm/dnamotif.rs
src/pattern_matching/pssm/mod.rs
src/pattern_matching/pssm/protmotif.rs
src/stats/pairhmm/homopolypairhmm.rs
src/stats/pairhmm/pairhmm.rs

I noticed some Clippy warnings being caused by the use of legacy numeric constants. 
I wrote about this in an issue I opened here: https://github.com/rust-bio/rust-bio/issues/643
I think fixing these kinds of issues would be good in case some of the legacy constants and methods are deprecated in a future version of Rust.
More info about this Clippy: https://rust-lang.github.io/rust-clippy/master/index.html#legacy_numeric_constants
In short, I made these kinds of changes:
- Removing std from numeric constants. Ex: std::usize::MAX -> usize::MAX
- Removing std from imports of numeric constants. Ex: use std::u8 -> use u8
The only Clippy warnings left concerning legacy numeric methods are those found by the use of <$DistType>::max_value() in lines 149 and 185 in …

refactor: Clippy warnings caused by legacy numeric constants
